image:
- Visual Studio 2017
- Ubuntu1804

environment:
  APPVEYOR_YML_DISABLE_PS_LINUX: true

services:
- docker

stack: node 10

install:
- sh: npm i -g gulp
- ps: choco install cloc --no-progress
- ps: "cloc --include-lang C#,SQL,Razor,\"Bourne Shell\",PowerShell,HTML,CSS,Sass,JavaScript,TypeScript --vcs git"

before_build:
#- sh: dotnet restore
- ps: msbuild /t:restore

build_script:
- sh: chmod +x ./build-ci.sh
- sh: ./build-ci.sh
- ps: >-
    msbuild bitwarden-server.sln /p:Configuration=Debug /verbosity:minimal
        /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
- ps: >-
    $env:swaggerGen="true"
    $env:ASPNETCORE_ENVIRONMENT="Production"
    cd .\src\Api; dotnet swagger tofile --output ..\..\swagger.json --host api.bitwarden.com --format Indented `
        .\bin\Debug\netcoreapp2.1\Api.dll public
    cd ..\..
    $env:ASPNETCORE_ENVIRONMENT=""
    $env:swaggerGen=""

after_build:
- sh: docker logout

test_script:
#- sh: dotnet test .\test\Core.Test\Core.Test.csproj --configuration Debug --no-build
- ps: dotnet test .\test\Core.Test\Core.Test.csproj --configuration Debug --no-build
