version: '3'

services:
  mssql:
    image: bitwarden/mssql:1.12.1
    container_name: mssql
    restart: always
      
  web:
    image: bitwarden/web:1.18.0
    container_name: web
    restart: always
    
  attachments:
    image: bitwarden/attachments:1.12.1
    container_name: attachments
    restart: always

  api:
    image: bitwarden/api:1.12.1
    container_name: api
    restart: always

  identity:
    image: bitwarden/identity:1.12.1
    container_name: identity
    restart: always

  nginx:
    image: bitwarden/nginx:1.12.1
    container_name: nginx
    restart: always
    ports:
      - '80:80'
      - '443:443'
