version: '3'

services:
  mssql:
    image: microsoft/mssql-server-linux
    container_name: mssql
    restart: always
    ports:
      - '1433:1433'
      
  web:
    image: bitwarden/web
    container_name: web
    restart: always
    
  attachments:
    image: bitwarden/attachments
    container_name: attachments
    restart: always

  api:
    image: bitwarden/api
    container_name: api
    restart: always

  identity:
    image: bitwarden/identity
    container_name: identity

  nginx:
    image: bitwarden/nginx
    container_name: nginx
    restart: always
    ports:
      - '80:80'
      - '443:443'
