version: '3'

services:
  mssql:
    volumes:
      - mssql_data:/var/opt/mssql/data
    env_file:
      - mssql.env
      - c:/bitwarden/docker/mssql.override.env
  web:
    volumes:
      - c:/bitwarden/web:/etc/bitwarden/web
  attachments:
    volumes:
      - c:/bitwarden/core/attachments:/etc/bitwarden/core/attachments
  api:
    volumes:
      - c:/bitwarden/core:/etc/bitwarden/core
    env_file:
      - global.env
      - c:/bitwarden/docker/global.override.env
  identity:
    volumes:
      - c:/bitwarden/identity:/etc/bitwarden/identity
      - c:/bitwarden/core:/etc/bitwarden/core
    env_file:
      - global.env
      - c:/bitwarden/docker/global.override.env
  nginx:
    volumes:
      - c:/bitwarden/nginx:/etc/bitwarden/nginx
      - c:/bitwarden/letsencrypt:/etc/letsencrypt
      - c:/bitwarden/ssl:/etc/ssl
volumes:
  mssql_data:
