version: '3'

services:
  mssql:
    volumes:
      - mssql_data:/var/opt/mssql/data
  api:
    volumes:
      - c:/bitwarden/core:/etc/core
  identity:
    volumes:
      - c:/bitwarden/core:/etc/core
  nginx:
    volumes:
      - c:/bitwarden/letsencrypt:/etc/letsencrypt
volumes:
  mssql_data:
