version: '3'

services:
  mssql:
    image: microsoft/mssql-server-linux
    container_name: mssql
    restart: always
    env_file:
      - mssql.env
      - mssql.override.env
    ports:
      - '1433:1433'

  api:
    image: bitwarden/api
    container_name: api
    restart: always
    env_file:
      - global.env
      - global.override.env

  identity:
    image: bitwarden/identity
    container_name: identity
    env_file:
      - global.env
      - global.override.env

  nginx:
    image: bitwarden/nginx
    container_name: nginx
    restart: always
    ports:
      - '80:80'
      - '443:443'
